version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  build:
    docker:
      - image: bufferings/cimg-cue
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            cd .circleci/configs
            cue export sample1.yaml sample2.yaml sample9.yaml --out yaml > ../generated_config.yml
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml
