version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  build:
    docker:
      - image: bufferings/cimg-cue
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            cd .circleci/configs
            find . -type f -name "*.yml" | awk '{printf "\"%s\"" ", $0}' \
            | xargs -0 -I {} sh -c 'cue export {} --out yaml' | tee ../generated_config.yml
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml
